apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-nfs-pv
  namespace: shared-services
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteMany 
  nfs: 
    path: /var/rabbitmq/ 
    server: 192.168.56.101 
  persistentVolumeReclaimPolicy: Retain
